// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg5s2I61TtBuolCBf3flhe2r0AZrwh9N8',
    appId: '1:748823516401:web:012b798c42bcf55c9ec550',
    messagingSenderId: '748823516401',
    projectId: 'permabliss-a7c5a',
    authDomain: 'permabliss-a7c5a.firebaseapp.com',
    storageBucket: 'permabliss-a7c5a.appspot.com',
    measurementId: 'G-XSD9KGFGTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7az_WPzHLiYp-ATSzUqkCDCCOBY4Yi4',
    appId: '1:748823516401:android:8d51d0e438225cfb9ec550',
    messagingSenderId: '748823516401',
    projectId: 'permabliss-a7c5a',
    storageBucket: 'permabliss-a7c5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRX_LLxYl2wNthKK_3llh-xVga6crGosA',
    appId: '1:748823516401:ios:89e3fd8ad280ffb19ec550',
    messagingSenderId: '748823516401',
    projectId: 'permabliss-a7c5a',
    storageBucket: 'permabliss-a7c5a.appspot.com',
    iosBundleId: 'com.ziehro.usdaZonePlants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRX_LLxYl2wNthKK_3llh-xVga6crGosA',
    appId: '1:748823516401:ios:c383b5b0a0d2af019ec550',
    messagingSenderId: '748823516401',
    projectId: 'permabliss-a7c5a',
    storageBucket: 'permabliss-a7c5a.appspot.com',
    iosBundleId: 'com.ziehro.usdaZonePlants.RunnerTests',
  );
}
